### ISSUE TITLE
Kernel building script not working for ARM64

### ISSUE THREAD

**Issue by StarOnTheSky** [ClangBuiltLinux/tc-build#184]
**Describe the bug**
Github Actions failed on the step `Build kernel`
Backtrace:
```
  bash ci-arm.sh kernel
  shell: /usr/bin/bash -e {0}

=============================
== Toolchain information ==
=============================

ClangBuiltLinux clang version 13.0.1 (https://github.com/llvm/llvm-project 75e33f71c2dae584b13a7d1186ae0a038ba98838)
Target: aarch64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/ubuntu/ci/actions-runner/_work/tc-build/tc-build/install/bin
+ for TARGET in "${TARGETS[@]}"

+ MAKE=("${MAKE_BASE[@]}")
========================
+ can_use_llvm_ias aarch64-linux-gnu
+ local llvm_version
== Building kernels ==
++ /home/ubuntu/ci/actions-runner/_work/tc-build/tc-build/clang-version.sh clang
========================

+ llvm_version=130001
+ case $1 in
+ [[ 130001 -ge 110000 ]]
+ return 0
+ case ${TARGET} in
+ make -skj4 KCFLAGS=-Wno-error LLVM=1 O=out ARCH=arm64 distclean defconfig all
error: unable to create target: 'No available targets are compatible with triple "thumbv8-unknown-linux-gnueabi"'
1 error generated.
make[3]: *** [../arch/arm64/kernel/vdso32/Makefile:153: arch/arm64/kernel/vdso32/note.o] Error 1
error: unable to create target: 'No available targets are compatible with triple "thumbv8-unknown-linux-gnueabi"'
1 error generated.
make[3]: *** [../arch/arm64/kernel/vdso32/Makefile:155: arch/arm64/kernel/vdso32/vgettimeofday.o] Error 1
make[3]: Target 'include/generated/vdso32-offsets.h' not remade because of errors.
make[3]: Target 'arch/arm64/kernel/vdso32/vdso.so' not remade because of errors.
make[2]: *** [../arch/arm64/Makefile:200: vdso_prepare] Error 2
make[2]: Target 'all' not remade because of errors.
make[1]: *** [/home/ubuntu/ci/actions-runner/_work/tc-build/tc-build/kernel/linux-5.17/Makefile:350: __build_one_by_one] Error 2
make[1]: Target 'distclean' not remade because of errors.
make[1]: Target 'defconfig' not remade because of errors.
make[1]: Target 'all' not remade because of errors.
make: *** [Makefile:219：__sub-make] 错误 2
make: 由于错误目标“distclean”并未重新制作。
make: 由于错误目标“defconfig”并未重新制作。
make: 由于错误目标“all”并未重新制作。

real	0m11.683s
user	0m26.548s
sys	0m9.586s
+ exit 2

Error: Process completed with exit code 2.
```

**To Reproduce**
PR: https://github.com/StarOnTheSky/tc-build/pull/1
File `.github/workflow/build-arm.yml`:
```
name: Build test (ARM64)
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  build-test:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: bash ci-arm.sh deps

    - name: Build LLVM
      run: bash ci-arm.sh llvm

    - name: Build binutils
      run: bash ci-arm.sh binutils

    - name: Build kernel
      run: bash ci-arm.sh kernel

    - name: Pack Artifact
      run: bash ci-arm.sh pack

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Toolchain Pack
        path: toolchain-arm64.tar.xz
```
File `ci-arm.sh`:
```
#!/usr/bin/env bash

BASE=$(dirname "$(readlink -f "${0}")")

set -eu

function parse_parameters() {
    while ((${#})); do
        case ${1} in
            all | binutils | deps | kernel | llvm | pack) ACTION=${1} ;;
            *) exit 33 ;;
        esac
        shift
    done
}

function do_all() {
    do_deps
    do_llvm
    do_binutils
    do_kernel
}

function do_binutils() {
    "${BASE}"/build-binutils.py -t aarch64
}

function do_deps() {
    # We only run this when running on GitHub Actions
    [[ -z ${GITHUB_ACTIONS:-} ]] && return 0
    sudo apt-get install -y --no-install-recommends \
        bc \
        bison \
        ca-certificates \
        clang \
        cmake \
        curl \
        file \
        flex \
        gcc \
        g++ \
        git \
        libelf-dev \
        libssl-dev \
        lld \
        make \
        ninja-build \
        python3 \
        texinfo \
        xz-utils \
        zlib1g-dev
}

function do_kernel() {
    cd "${BASE}"/kernel
    ./build.sh -t AArch64
}

function do_llvm() {
    EXTRA_ARGS=()
    [[ -n ${GITHUB_ACTIONS:-} ]] && EXTRA_ARGS+=(--no-ccache)
    "${BASE}"/build-llvm.py \
        --assertions \
        --branch "release/13.x" \
        --build-stage1-only \
        --check-targets clang lld llvm \
        --install-stage1-only \
        --projects "clang;lld" \
        --shallow-clone \
        --targets AArch64 \
        "${EXTRA_ARGS[@]}"
}

function do_pack() {
    cd "${BASE}"
    mv install toolchain
    tar Jcf toolchain.tar.xz toolchain
}

parse_parameters "${@}"
do_"${ACTION:=all}"

```

**Expected behavior**
Actions finished without error.

**Environment (please complete the following information):**
  - Command you ran: [e.g. `./build-llvm.py`] Described above.
  - Distribution: [e.g. Debian stretch or Arch Linux] Ubuntu 20.04 ARM64
  - Python version: [e.g. 3.7.3] 3.8.10
  - Shell: [e.g. zsh] May be `bash`
